### ISSUE TITLE
Not able to connect mysql container prompt

### ISSUE THREAD

**Issue by kumarshorav11** [serainville/serverlab-kubernetes-templates#1]
Hi,
Mysql pod (5.7) is up and running. Now, I am able to enter by
kubectl exec -it <pod_name> -n namespace.

Inside the mysql pod
# mysql -u root -p 
password : <secret key password >

but I am getting error -
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
I am not able to point what I am doing wrong?
Please help me out.
Thanks for your time.

**Comment by serainville** [comment]
I was able to recreate your issue and worked around it by entering the secrets' values directly, as plain text, into the deployment manifest. There appears to be an issue with the secrets data. 

I will continue to investigate the problem.

**Comment by serainville** [comment]
Secrets in demo file were improperly base64 encoded. Extra string data was entered.

On OSX secrets must be base64 encoded using command `echo -n 'secret-string' | base64`.

Alternatively, a secrets manifest can be populated using `stringData`.

```yaml
apiVersion: v1
kind: Secrets
metadata:
  name: mysql-secrets
stringData:
  MYSQL_ROOT_PASSWORD: "SuperSecretPassword"
```
